baseURL = "https://www.example.com"
languageCode = "en-us"
title = "My Digital Garden"
theme = "digital-garden"
publishDir = 'docs'
copyright = "LMD-ECRAX* ©"


[params]
  name = "LMD Early Career Researchers' Assembly"
  description = "A bunch of young adults thinking they can be researchers."
  initials = "LMD-ECRAX"
  googleAnalytics = ""

[menu]
  [[menu.main]]
    name = "Meeting Schedule"
    url = "/meetings/"
    weight = 1
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[taxonomies]
  meeting_tags = 'meeting_tags'
  news_tags = 'news_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
